##
# Let's Encrypt Service
#
# This is the daemon version of the service. HTTP/HTTPS ports are enabled.
# This Config will NOT be used if both the panel and daemon 
##
version: '2.1'
services:
  certbot:
    command: renew
    image: certbot/certbot
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./conf.d/letsencrypt:/etc/letsencrypt
