version: '2.3'
services:
  ##
  # --Pterodactyl Panel--
  # This is the container that provides the main web interface.
  ##
  panel:
    depends_on:
      cache:
        condition: service_started
    env_file: ./conf.d/panel.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 1m
    image: ccarney16/pterodactyl-panel:latest
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - ./data/panel:/data
    # Enable Let's Encrypt Support
    - ./conf.d/letsencrypt:/etc/letsencrypt
    - ./conf.d/letsencrypt/webroot/.well-known:/var/www/html/public/.well-known
    - ./conf.d/certs:/etc/certs
  ##
  # --Worker--
  # These are required for schedules and other misc tasks to 
  # function correctly.
  ##
  worker:
    command: p:worker
    depends_on:
      panel:
        condition: service_healthy
    env_file: ./conf.d/panel.env
    image: ccarney16/pterodactyl-panel:latest
    restart: always
    volumes_from:
    - panel
  ##
  # --Cron--
  # These are required for schedules and other misc tasks to 
  # function correctly.
  ##
  cron:
    command: p:cron
    depends_on:
      panel:
        condition: service_healthy
    env_file: ./conf.d/panel.env
    image: ccarney16/pterodactyl-panel:latest
    restart: always
    volumes_from:
    - panel
  ##
  # --Redis--
  # Handles Session Data
  ##
  cache:
    image: redis:alpine
    restart: always