version: '2.3'
services:
  ##
  # --Pterodactyl Panel--
  # This is the container that provides the main web interface.
  ##
  panel:
    depends_on:
      cache:
        condition: service_started
    env_file: ./conf.d/panel.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 1m
    image: ccarney16/pterodactyl-panel:latest
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - ./data/panel:/data
    # Enable Let's Encrypt Support
    - ./conf.d/letsencrypt:/etc/letsencrypt
    - ./conf.d/letsencrypt/webroot/.well-known:/var/www/html/public/.well-known
    - ./conf.d/certs:/etc/certs
  ##
  # --Worker--
  # These are required for schedules and other misc tasks to 
  # function correctly.
  ##
  worker:
    command: p:worker
    depends_on:
      panel:
        condition: service_healthy
    env_file: ./conf.d/panel.env
    image: ccarney16/pterodactyl-panel:latest
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.pqueue.schedule: "@every 1m"
      ofelia.job-exec.pqueue.command: "php /var/www/html/artisan schedule:run"
      ofelia.job-exec.pqueue.user: "nginx"
    restart: always
    volumes_from:
    - panel
  cron:
    command: daemon --docker
    depends_on:
      panel:
        condition: service_healthy
      worker:
        condition: service_started
    image: mcuadros/ofelia:latest
    network_mode: none
    privileged: true
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ##
  # --Redis--
  # Handles Session Data
  ##
  cache:
    cpu_count: 2
    cpu_percent: 50
    image: redis:alpine
    mem_limit: 128m
    pids_limit: 5
    restart: always