##
# Let's Encrypt Service
#
# This is the daemon version of the service. HTTP/HTTPS ports are enabled.
# This Config will NOT be used if both the panel and daemon 
##
version: '2.3'
services:
  certbot:
    container_name: pterodactyl_certbot
    image: certbot/certbot:latest
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.le-renew.schedule: "0 0 * * *"
      ofelia.job-run.le-renew.container: pterodactyl_certbot
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./conf.d/letsencrypt:/etc/letsencrypt
  cron:
    command: daemon --docker
    depends_on:
      certbot:
        condition: service_started
      daemon:
        condition: service_started
    image: mcuadros/ofelia:latest
    network_mode: none
    privileged: true
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  daemon:
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.daemon-reload.schedule: "${DAEMON_RELOAD_SCHEDULE:-0 30 * * *}"
      ofelia.job-exec.daemon-reload.command: "kill -15 1"
